# Exclusive configuration for TeamCity, poetry is already installed there.
name: vrtool_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-forge::python=3.12
  - conda-forge::openturns=1.24
  - conda-forge::matplotlib=3.10.3
